sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t ItayBracha11/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true ItayBracha11/react-test npm test

after_success:
  - docker build -t ItayBracha11/multi-client ./client
  - docker build -t ItayBracha11/multi-nginx ./nginx
  - docker build -t ItayBracha11/multi-server ./server
  - docker build -t ItayBracha11/multi-worker ./worker

